/**
 * The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

 Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
 10: 1,2,5,10
 15: 1,3,5,15
 21: 1,3,7,21
 28: 1,2,4,7,14,28
 We can see that 28 is the first triangle number to have over five divisors.

 What is the value of the first triangle number to have over five hundred divisors?
 */
public class problem12 {
    public static void main(String[] args) {
        int iterator = 2;
        int triangle = 1;
        boolean found = false;
        do {
            if(getNumDiv(triangle) > 500) {
                found = true;
            } else {
                triangle = triangle + iterator;
                iterator++;
            }
        }while(!found);
        System.out.println("The answer is: " + triangle);
    }

    public static int getNumDiv(int num) {
        int count = 0;
        for(int ii = 1; ii*ii <= num; ii++) {
            if(num % ii == 0){
                if(ii * ii < num) {
                    count+=2;
                } else {
                    count++;
                }
            }
        }
        return count;
    }
}
