/**
 * Problem 2 prompt:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms
 */
public class problem2 {
    public static void main (String[] args){
        problem2(); //call function
    }

    public static void problem2(){
        int firstNum = 1; //known first value of fibonacci
        int nextNum = 2; //known second value of fibonacci
        int temp;
        int sum = 2; //taking account for first even number being 2
        while(sum < 4000000)
        {
            temp = firstNum + nextNum;
            firstNum = nextNum;
            nextNum = temp;

            if(temp % 2 == 0) //checking if even number
            {
                sum += temp;
            }
        }

        System.out.println("The answer is: " + sum);
    }
}
